# Generated by Django 3.2.9 on 2021-12-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
